name: Scan for GitHub Actions issues

on:
  pull_request:
  workflow_call:

concurrency:
  group: github-actions-linter-${{ github.event.pull_request.number }}${{ github.event_name == 'workflow_call' && '-test' }}

permissions: {}

jobs:
  main:
    name: Scan repository contents
    runs-on: cx-public-ubuntu-x64
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Zizmor linter
        uses: step-security/zizmor-action@6dc1b15aa3aca5de1faf70db0f8214e26c5ebbe9 # v0.6.2
        with:
          advanced-security: false
          annotations: false
          persona: pedantic
          fail-on-no-inputs: false
          # TODO: Zizmor needs a token so it can read actions from other internal repos.
          online-audits: false
